# Site settings
title: Beegit Jekyll Theme
email: support@beegit.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
input: GFM
permalink: pretty
paginate: 10

# Author details - do not mess with formatting
mike_cottrill:
    name: Mike Cottrill
    email: mike@beegit.com
    web: https://twitter.com/mrcottrill
    gravatar: http://www.gravatar.com/avatar/bfbf8a5493bb3666498f27760928707b.jpg?s=64
    details: Co-founder and CEO of Beegit. Content marketer and recovering journalist. All blog posts planned and made fresh in Cleveland, Ohio.  
jd_eaton:
    name: JD Eaton
    email: jd@beegit.com
    web: https://twitter.com/designerjde
    gravatar: http://www.gravatar.com/avatar/8429349471db2768937fba6126c9fded.jpg?s=64
    details: Co-founder and CMO at Beegit. Communications designer and agent of simplicity. Made in Cleveland, Ohio.
kris_ciccarello:
    name: Kris Ciccarello
    email: kris@beegit.com
    web: https://twitter.com/kmctown
    gravatar: http://www.gravatar.com/avatar/d703f18bac83300f8c935b5bff605237.jpg?s=64
    details: Co-founder and CTO of Beegit. Lifetime coder and problem reducer. Slinging bits in Cleveland, Ohio.
thom_parkin:
    name: Thom Parkin
    email: thom.parkin@websembly.com
    web: https://www.packtpub.com/application-development/mastering-git-video
    gravatar: https://s3.amazonaws.com/beegit-images/blog/avatars/thom-parkin.png
    details: Thom Parkin has been writing software since the time when all phones had wires. He is a technical teacher, author and has been a self-proclaimed ParaHacker for more than 30 years. As an early adopter of git, Thom has been evangelizing this favored SCM to a larger audience; namely everyone else who is NOT a software developer.
